### ISSUE TITLE
Feature request - Shader Support

### ISSUE THREAD

**Issue by campbebj** [CebbysMods/slabref-mod#11]
any thoughts on adding shader support? right now the blocks dissapear when shaders are turned on.

**Comment by CebbyS** [comment]
Interesting... are you using optifine?

**Comment by campbebj** [comment]
Yup.

**Comment by CebbyS** [comment]
If I understand correctly, Its because of conflicts between optifine and fabric rendering api. You can check out this issue page on optifabric mod https://github.com/modmuss50/OptiFabric/issues/10

I dont think that I can fix this, without a different rendering methods for my mod.

**Comment by campbebj** [comment]
ok cool, i might check out if theres a different shaders mod and see if
that works.
