### ISSUE TITLE
Placing anything on/under slabs completely replaces the slab

### ISSUE THREAD

**Issue by SplendidAlakey** [CebbysMods/slabref-mod#16]
**MC** 1.18.2
**Fabric API** 0.55.1
**Refabricated Slabs** 0.6.0.a

To reproduce:

1. Place any slab down
2. Place anything else (other than slabs) on top of it
3. The slab gets completely replaced by whatever you just placed

Works the same way with upper slabs when you place anything under them.

Logs: https://gist.github.com/Footage2-Amply-Pounce/34e62977b7c52e5c5246719eb89a1d4f

**Comment by CebbyS** [comment]
Thank you for the bug report! This has been resolved in the latest patch!
