### ISSUE TITLE
Invisible block

### ISSUE THREAD

**Issue by SandWoodJones** [CebbysMods/slabref-mod#19]
I was getting the missing texture bug before realizing there was a resource pack. I enabled the resource pack but it didn't fix the problem and now mixed slabs look like this:
![image](https://user-images.githubusercontent.com/35671374/175753459-d41357f5-1753-49b8-99b2-aa3672cfbfbe.png)

**Comment by CebbyS** [comment]
Hi, Is it in version 0.6.4?

**Comment by ShaneTRS** [comment]
I have the same issue. 0.6.4
The problem is an incompatibility with Sodium (with and without Indium).

**Comment by ShaneTRS** [comment]
@CebbyS Just wanted to make sure you were aware that it was recreated and has to do with Sodium.

**Comment by CebbyS** [comment]
Hi, @ShaneTRS!

Thanks for the report! I will try to investigate how to work around this.
Its nice to have a clue, that the issue is with Sodium

**Comment by CebbyS** [comment]
Hi, @ShaneTRS, @SandWoodJones!

I have updated the mod to version 0.7.1. This version should fix the issues with sodium, fabric and iris.
Can you please confirm that everything is working correctly?

Thanks!

**Comment by SandWoodJones** [comment]
I can confirm its working.
