### ISSUE TITLE
This doesn't seem to support Blockus and Better End.

### ISSUE THREAD

**Issue by Boodlyneck** [CebbysMods/slabref-mod#3]
I'm using slabref-0.1.1, celib-0.2.1, blockus-2.0.1, and better-end-0.8.3-beta.
Vanilla slabs work as expected, but blockus and better end slabs use vanilla slab behavior.

**Comment by CibaTheDev** [comment]
Hello,
I am working on a update that should resolve the issue. I will try to
update my mod in the following days.
Thankyou for informing me about the problem!

Boodlyneck <notifications@github.com> (šajā datumā: Sv, 2020. g. 27. dec.
23:54) rakstīja:

**Comment by CebbyS** [comment]
Fixed support for Blockus and Better End
